<?php

declare(strict_types=1);

namespace Morozov\PgCompat\DB\Ddl;

use Morozov\PgCompat\DB\Dialect\NameResolver;
use Morozov\PgCompat\DB\Dialect\TypeMapper;

/**
 * Translates a single MySQL DDL fragment (a column/constraint definition, or a whole
 * CREATE/ALTER TABLE body) into Postgres syntax.
 *
 * This is the fallback path for seams that only ever hand us pre-rendered MySQL SQL
 * text rather than Magento's structured Table/Column DTOs:
 *  - Declarative-schema Definition processors (Magento\Framework\Setup\Declaration\
 *    Schema\Db\MySQL\Definition\*) render fragments as strings before DbSchemaWriter
 *    ever sees them - there is no DTO to intercept at that seam without a parallel
 *    Postgres-native Definition processor set (a larger, separate change).
 *  - Legacy install/upgrade scripts that build ALTER TABLE text by hand (MODIFY COLUMN
 *    and similar) instead of using the Table DDL API.
 *
 * The imperative path (Table::addColumn()/createTable()) does NOT go through here -
 * Morozov\PgCompat\DB\Adapter\Pdo\Postgres builds Postgres DDL directly from the
 * Table/Column DTOs via ColumnDefinitionBuilder/IndexDefinitionBuilder, since that
 * data is available there without ever rendering a MySQL string first.
 */
class MysqlToPostgres
{
    public function __construct(
        private readonly TypeMapper $types,
        private readonly NameResolver $names
    ) {
    }

    public function translateFragment(string $fragment, ?string $tableName = null): string
    {
        $sql = $this->quoteIdentifiers($fragment);
        foreach ($this->types->keywordReplacements() as [$pattern, $replacement]) {
            $sql = preg_replace($pattern, $replacement, $sql);
        }
        $sql = preg_replace('/\bAUTO_INCREMENT\b/i', 'GENERATED BY DEFAULT AS IDENTITY', $sql);
        $sql = preg_replace('/\s+ON UPDATE CURRENT_TIMESTAMP\b/i', '', $sql);
        $sql = preg_replace('/\s+CHARACTER SET\s+\w+/i', '', $sql);
        $sql = preg_replace('/\s+COLLATE\s+\w+/i', '', $sql);
        $sql = preg_replace('/\s+COMMENT\s+([\'"]).+?\1/i', '', $sql);
        $sql = preg_replace("/NOT NULL DEFAULT '0000-00-00 00:00:00'/i", "NOT NULL DEFAULT '1970-01-01 00:00:00'", $sql);
        $sql = preg_replace("/DEFAULT '0000-00-00 00:00:00'/i", 'DEFAULT NULL', $sql);
        $sql = preg_replace(
            '/\b(timestamp|date)\s+((?:NOT\s+)?NULL\s+)?DEFAULT 0\b/i',
            "$1 $2DEFAULT '1970-01-01 00:00:00'",
            $sql
        );
        $sql = preg_replace('/DEFAULT\s+"([^"]*)"/', "DEFAULT '$1'", $sql);
        $sql = preg_replace('/\bUNIQUE KEY\b/i', 'UNIQUE', $sql);
        $sql = preg_replace('/\bCONSTRAINT\s+PRIMARY KEY\b/i', 'PRIMARY KEY', $sql);
        $sql = preg_replace(
            '/("[A-Za-z0-9_]+"\s+(?:varchar\s*\([^)]+\)|text|jsonb))\s+NOT NULL(?!\s+DEFAULT)(?!\s+GENERATED)/i',
            '$1 NOT NULL DEFAULT \'\'',
            $sql
        );
        $sql = preg_replace(
            '/("[A-Za-z0-9_]+"\s+(?:smallint|integer|bigint|numeric\s*\([^)]+\)|real|double precision))\s+NOT NULL(?!\s+DEFAULT)(?!\s+GENERATED)/i',
            '$1 NOT NULL DEFAULT 0',
            $sql
        );
        $sql = preg_replace(
            '/("[A-Za-z0-9_]+"\s+timestamp)\s+NOT NULL(?!\s+DEFAULT)/i',
            '$1 NOT NULL DEFAULT \'1970-01-01 00:00:00\'',
            $sql
        );
        $sql = $this->uniquifyConstraintNames($sql, $tableName);
        return trim(preg_replace('/[ \t]+/', ' ', $sql));
    }

    public function isIndexFragment(string $fragment): bool
    {
        $normalized = ltrim($this->quoteIdentifiers($fragment));
        return (bool) preg_match('/^(FULLTEXT\s+)?(INDEX|KEY)\s+/i', $normalized);
    }

    public function indexToCreateSql(string $tableName, string $fragment): ?string
    {
        $fragment = $this->quoteIdentifiers($fragment);
        if (preg_match('/FULLTEXT/i', $fragment)) {
            return null;
        }
        if (!preg_match('/(?:INDEX|KEY)\s+("?[A-Za-z0-9_]+"?)\s*\((.+)\)/is', $fragment, $m)) {
            return null;
        }
        $unique = (bool) preg_match('/^\s*UNIQUE\b/i', ltrim($fragment));
        $name = $this->names->relationName(trim($m[1], '"'), $tableName);
        $cols = preg_replace('/\(\d+\)/', '', $m[2]);
        return sprintf(
            'CREATE %sINDEX IF NOT EXISTS %s ON %s (%s)',
            $unique ? 'UNIQUE ' : '',
            $this->quote($name),
            $this->quote($tableName),
            $cols
        );
    }

    public function quoteIdentifiers(string $sql): string
    {
        return preg_replace_callback('/`([^`]+)`/', static function (array $m) {
            return '"' . str_replace('"', '""', $m[1]) . '"';
        }, $sql);
    }

    private function uniquifyConstraintNames(string $sql, ?string $tableName): string
    {
        if ($tableName === null || $tableName === '') {
            return $sql;
        }
        return preg_replace_callback('/\bCONSTRAINT\s+"([^"]+)"/', function (array $m) use ($tableName) {
            return 'CONSTRAINT "' . $this->names->constraintName($tableName, $m[1]) . '"';
        }, $sql);
    }

    private function quote(string $name): string
    {
        return '"' . str_replace('"', '""', $name) . '"';
    }
}
