<?php

declare(strict_types=1);

namespace Morozov\PgCompat\Test\Unit\DB\Ddl;

use Morozov\PgCompat\DB\Ddl\MysqlToPostgres;
use Morozov\PgCompat\DB\Dialect\NameResolver;
use Morozov\PgCompat\DB\Dialect\TypeMapper;
use PHPUnit\Framework\TestCase;

class MysqlToPostgresTest extends TestCase
{
    private MysqlToPostgres $translator;

    protected function setUp(): void
    {
        $this->translator = new MysqlToPostgres(new TypeMapper(), new NameResolver());
    }

    public function testQuotesBacktickedIdentifiers(): void
    {
        $this->assertSame('"col" int', $this->translator->quoteIdentifiers('`col` int'));
    }

    public function testTranslatesBigintUnsigned(): void
    {
        $result = $this->translator->translateFragment('"a" BIGINT UNSIGNED NOT NULL');
        $this->assertStringContainsString('bigint', $result);
        $this->assertStringNotContainsString('UNSIGNED', $result);
    }

    public function testTranslatesIntUnsignedToBigint(): void
    {
        $result = $this->translator->translateFragment('"a" INT UNSIGNED');
        $this->assertStringContainsString('bigint', $result);
    }

    public function testTranslatesTinyintOneToSmallint(): void
    {
        $result = $this->translator->translateFragment('"a" TINYINT(1) NOT NULL');
        $this->assertStringContainsString('smallint', $result);
    }

    public function testTranslatesJsonToJsonb(): void
    {
        $result = $this->translator->translateFragment('"a" JSON');
        $this->assertStringContainsString('jsonb', $result);
    }

    public function testAutoIncrementBecomesIdentity(): void
    {
        $result = $this->translator->translateFragment('"id" int AUTO_INCREMENT');
        $this->assertStringContainsString('GENERATED BY DEFAULT AS IDENTITY', $result);
    }

    public function testStripsCharacterSetAndCollate(): void
    {
        $result = $this->translator->translateFragment(
            '"a" varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci'
        );
        $this->assertStringNotContainsString('CHARACTER SET', $result);
        $this->assertStringNotContainsString('COLLATE', $result);
    }

    public function testStripsInlineComment(): void
    {
        $result = $this->translator->translateFragment('"a" int COMMENT \'some comment\'');
        $this->assertStringNotContainsString('COMMENT', $result);
        $this->assertStringNotContainsString('some comment', $result);
    }

    public function testZeroDateDefaultBecomesEpoch(): void
    {
        $result = $this->translator->translateFragment(
            "\"a\" timestamp NOT NULL DEFAULT '0000-00-00 00:00:00'"
        );
        $this->assertStringContainsString("DEFAULT '1970-01-01 00:00:00'", $result);
    }

    public function testUnnamedZeroDateDefaultBecomesNull(): void
    {
        $result = $this->translator->translateFragment("\"a\" timestamp DEFAULT '0000-00-00 00:00:00'");
        $this->assertStringContainsString('DEFAULT NULL', $result);
    }

    public function testNotNullVarcharWithoutDefaultBackfillsEmptyString(): void
    {
        $result = $this->translator->translateFragment('"a" varchar(50) NOT NULL');
        $this->assertStringContainsString("DEFAULT ''", $result);
    }

    public function testNotNullIntegerWithoutDefaultBackfillsZero(): void
    {
        $result = $this->translator->translateFragment('"a" integer NOT NULL');
        $this->assertStringContainsString('DEFAULT 0', $result);
    }

    public function testExistingDefaultIsNotOverwrittenByBackfill(): void
    {
        $result = $this->translator->translateFragment('"a" integer NOT NULL DEFAULT 5');
        $this->assertSame('"a" integer NOT NULL DEFAULT 5', $result);
    }

    public function testConstraintNameIsPrefixedWithTableName(): void
    {
        $result = $this->translator->translateFragment('CONSTRAINT "UNQ_SKU" UNIQUE ("sku")', 'catalog_product');
        $this->assertStringContainsString('"catalog_product_UNQ_SKU"', $result);
    }

    public function testConstraintNameIsUnchangedWithoutTableName(): void
    {
        $result = $this->translator->translateFragment('CONSTRAINT "UNQ_SKU" UNIQUE ("sku")');
        $this->assertStringContainsString('"UNQ_SKU"', $result);
    }

    public function testIsIndexFragmentDetectsPlainIndex(): void
    {
        $this->assertTrue($this->translator->isIndexFragment('INDEX `IDX_A` (`a`)'));
    }

    public function testIsIndexFragmentDetectsFulltext(): void
    {
        $this->assertTrue($this->translator->isIndexFragment('FULLTEXT INDEX `FTI_A` (`a`)'));
    }

    public function testIsIndexFragmentRejectsConstraint(): void
    {
        $this->assertFalse($this->translator->isIndexFragment('CONSTRAINT `UNQ_A` UNIQUE KEY (`a`)'));
    }

    public function testIndexToCreateSqlBuildsCreateIndexStatement(): void
    {
        $result = $this->translator->indexToCreateSql('catalog_product', 'INDEX `IDX_SKU` (`sku`)');
        $this->assertSame(
            'CREATE INDEX IF NOT EXISTS "catalog_product_IDX_SKU" ON "catalog_product" ("sku")',
            $result
        );
    }

    public function testIndexToCreateSqlReturnsNullForFulltext(): void
    {
        $this->assertNull($this->translator->indexToCreateSql('t', 'FULLTEXT INDEX `FTI_A` (`a`)'));
    }

    public function testIndexToCreateSqlStripsColumnPrefixLength(): void
    {
        $result = $this->translator->indexToCreateSql('t', 'INDEX `IDX_A` (`a`(191))');
        $this->assertStringContainsString('("a")', $result);
    }

    public function testIndexToCreateSqlDetectsUniquePrefix(): void
    {
        $result = $this->translator->indexToCreateSql('t', 'UNIQUE INDEX `UNQ_A` (`a`)');
        $this->assertStringContainsString('CREATE UNIQUE INDEX', $result);
    }
}
