<?php

declare(strict_types=1);

namespace Morozov\PgCompat\Setup\Declaration\Schema\Db\PgSQL\Definition\Columns;

use Magento\Framework\App\ResourceConnection;
use Magento\Framework\Setup\Declaration\Schema\Db\DbDefinitionProcessorInterface;
use Magento\Framework\Setup\Declaration\Schema\Db\MySQL\Definition\Columns\Integer as MysqlInteger;
use Magento\Framework\Setup\Declaration\Schema\Db\MySQL\Definition\Columns\Nullable;
use Magento\Framework\Setup\Declaration\Schema\Dto\ElementInterface;
use Morozov\PgCompat\DB\Dialect\ColumnDefinitionBuilder;
use Morozov\PgCompat\DB\Dialect\TypeMapper;

/**
 * Postgres-native replacement for MySQL\Definition\Columns\Integer (handles int/
 * smallint/tinyint/bigint). Postgres has no UNSIGNED - an unsigned int is widened to
 * bigint instead (same policy as the imperative Table-DDL path's TypeMapper::
 * toPostgres()), and AUTO_INCREMENT becomes GENERATED BY DEFAULT AS IDENTITY.
 *
 * fromDefinition() delegates to the original MySQL processor - see Boolean's docblock
 * for why that direction doesn't need changing.
 */
class Integer implements DbDefinitionProcessorInterface
{
    public function __construct(
        private readonly MysqlInteger $mysqlProcessor,
        private readonly Nullable $nullable,
        private readonly ResourceConnection $resourceConnection,
        private readonly ColumnDefinitionBuilder $columnBuilder,
        private readonly TypeMapper $types
    ) {
    }

    /**
     * @param \Magento\Framework\Setup\Declaration\Schema\Dto\Columns\Integer $column
     */
    public function toDefinition(ElementInterface $column)
    {
        $pgType = $this->types->declarativeTypeToPostgres($column->getType(), $column->isUnsigned());
        $nullableClause = $this->nullable->toDefinition($column);
        $sql = sprintf(
            '%s %s %s',
            $this->resourceConnection->getConnection()->quoteIdentifier($column->getName()),
            $pgType,
            $nullableClause
        );

        if ($column->isIdentity()) {
            return $sql . ' GENERATED BY DEFAULT AS IDENTITY';
        }
        if ($column->getDefault() !== null) {
            return $sql . $this->columnBuilder->explicitDefault((int) $column->getDefault());
        }
        if ($nullableClause === 'NOT NULL') {
            return $sql . $this->columnBuilder->implicitNotNullDefault($pgType);
        }
        return $sql;
    }

    public function fromDefinition(array $data)
    {
        return $this->mysqlProcessor->fromDefinition($data);
    }
}
