<?php

declare(strict_types=1);

namespace Morozov\PgCompat\Test\Unit\DB\Dialect;

use Magento\Framework\DB\Ddl\Table;
use Morozov\PgCompat\DB\Dialect\ColumnDefinitionBuilder;
use Morozov\PgCompat\DB\Dialect\TypeMapper;
use PHPUnit\Framework\TestCase;

class ColumnDefinitionBuilderTest extends TestCase
{
    private ColumnDefinitionBuilder $builder;

    protected function setUp(): void
    {
        $this->builder = new ColumnDefinitionBuilder(new TypeMapper());
    }

    public function testNullableColumnWithNoDefaultOmitsDefaultClause(): void
    {
        $sql = $this->builder->build(Table::TYPE_INTEGER, ['NULLABLE' => true]);
        $this->assertSame('integer NULL', $sql);
    }

    public function testNotNullIntegerWithoutDefaultBackfillsZero(): void
    {
        $sql = $this->builder->build(Table::TYPE_INTEGER, ['NULLABLE' => false]);
        $this->assertSame('integer NOT NULL DEFAULT 0', $sql);
    }

    public function testNotNullVarcharWithoutDefaultBackfillsEmptyString(): void
    {
        $sql = $this->builder->build(Table::TYPE_TEXT, ['NULLABLE' => false, 'LENGTH' => 50]);
        $this->assertSame("varchar(50) NOT NULL DEFAULT ''", $sql);
    }

    public function testNotNullTimestampWithoutDefaultBackfillsEpoch(): void
    {
        $sql = $this->builder->build(Table::TYPE_TIMESTAMP, ['NULLABLE' => false]);
        $this->assertSame("timestamp NOT NULL DEFAULT '1970-01-01 00:00:00'", $sql);
    }

    public function testNullableTimestampWithoutDefaultIsExplicitlyNull(): void
    {
        $sql = $this->builder->build(Table::TYPE_TIMESTAMP, ['NULLABLE' => true]);
        $this->assertSame('timestamp NULL DEFAULT NULL', $sql);
    }

    public function testTimestampInitSentinelBecomesCurrentTimestamp(): void
    {
        $sql = $this->builder->build(
            Table::TYPE_TIMESTAMP,
            ['NULLABLE' => false, 'DEFAULT' => Table::TIMESTAMP_INIT]
        );
        $this->assertSame('timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP', $sql);
    }

    public function testTimestampUpdateSentinelBecomesCurrentTimestamp(): void
    {
        $sql = $this->builder->build(
            Table::TYPE_TIMESTAMP,
            ['NULLABLE' => false, 'DEFAULT' => Table::TIMESTAMP_UPDATE]
        );
        $this->assertSame('timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP', $sql);
    }

    public function testExplicitNumericDefaultIsNotQuoted(): void
    {
        $sql = $this->builder->build(Table::TYPE_INTEGER, ['NULLABLE' => false, 'DEFAULT' => 42]);
        $this->assertSame('integer NOT NULL DEFAULT 42', $sql);
    }

    public function testExplicitStringDefaultIsSingleQuoted(): void
    {
        $sql = $this->builder->build(Table::TYPE_TEXT, ['NULLABLE' => false, 'LENGTH' => 20, 'DEFAULT' => "it's"]);
        $this->assertSame("varchar(20) NOT NULL DEFAULT 'it''s'", $sql);
    }

    public function testExplicitZendDbExprDefaultIsUsedVerbatim(): void
    {
        $sql = $this->builder->build(
            Table::TYPE_INTEGER,
            ['NULLABLE' => false, 'DEFAULT' => new \Zend_Db_Expr('nextval(\'seq\')')]
        );
        $this->assertSame("integer NOT NULL DEFAULT nextval('seq')", $sql);
    }

    public function testIdentityColumnGetsGeneratedByDefaultAsIdentity(): void
    {
        $sql = $this->builder->build(Table::TYPE_INTEGER, ['NULLABLE' => false, 'IDENTITY' => true]);
        $this->assertSame('integer NOT NULL GENERATED BY DEFAULT AS IDENTITY', $sql);
    }

    public function testIdentityColumnWithoutExplicitNullableIsStillNotNull(): void
    {
        // Table::addColumn(..., ['identity' => true, 'primary' => true]) - the shape
        // Magento core actually uses - leaves NULLABLE unset, defaulting to nullable=true.
        // Postgres identity columns are implicitly NOT NULL; declaring "NULL GENERATED BY
        // DEFAULT AS IDENTITY" is a syntax error, so this must render NOT NULL regardless.
        $sql = $this->builder->build(Table::TYPE_INTEGER, ['IDENTITY' => true]);
        $this->assertSame('integer NOT NULL GENERATED BY DEFAULT AS IDENTITY', $sql);
    }

    public function testIdentityViaAutoIncrementOptionIsEquivalent(): void
    {
        $sql = $this->builder->build(Table::TYPE_INTEGER, ['NULLABLE' => false, 'AUTO_INCREMENT' => true]);
        $this->assertStringContainsString('GENERATED BY DEFAULT AS IDENTITY', $sql);
    }

    public function testIdentityColumnIgnoresAnyExplicitDefault(): void
    {
        $sql = $this->builder->build(
            Table::TYPE_INTEGER,
            ['NULLABLE' => false, 'IDENTITY' => true, 'DEFAULT' => 99]
        );
        $this->assertStringNotContainsString('DEFAULT 99', $sql);
        $this->assertStringContainsString('GENERATED BY DEFAULT AS IDENTITY', $sql);
    }

    public function testUnsignedIntegerWidensToBigint(): void
    {
        $sql = $this->builder->build(Table::TYPE_INTEGER, ['NULLABLE' => true, 'UNSIGNED' => true]);
        $this->assertStringStartsWith('bigint', $sql);
    }

    public function testNullableIsDefaultTrueWhenOmitted(): void
    {
        $sql = $this->builder->build(Table::TYPE_INTEGER, []);
        $this->assertSame('integer NULL', $sql);
    }

    public function testBlobFamilyHasNoImplicitBackfill(): void
    {
        // Postgres bytea has no meaningful zero-ish default; matches historical
        // regex-based behavior of leaving it alone.
        $sql = $this->builder->build(Table::TYPE_BLOB, ['NULLABLE' => false]);
        $this->assertSame('bytea NOT NULL', $sql);
    }
}
