<?php

declare(strict_types=1);

namespace Morozov\PgCompat\Test\Unit\DB\Dialect;

use Magento\Framework\DB\Ddl\Table;
use Morozov\PgCompat\DB\Dialect\ColumnDefinitionBuilder;
use Morozov\PgCompat\DB\Dialect\IndexDefinitionBuilder;
use Morozov\PgCompat\DB\Dialect\NameResolver;
use Morozov\PgCompat\DB\Dialect\TableSql;
use Morozov\PgCompat\DB\Dialect\TypeMapper;
use PHPUnit\Framework\TestCase;

class TableSqlTest extends TestCase
{
    public function testCreateTableAssemblesColumnsAndPrimaryKey(): void
    {
        $names = new NameResolver();
        $tableSql = new TableSql(
            new ColumnDefinitionBuilder(new TypeMapper()),
            new IndexDefinitionBuilder($names),
            $names
        );

        $table = $this->createMock(Table::class);
        $table->method('getName')->willReturn('catalog_example');
        $table->method('getColumns')->willReturn([
            [
                'COLUMN_NAME' => 'entity_id',
                'TYPE' => Table::TYPE_INTEGER,
                'NULLABLE' => false,
                'PRIMARY' => true,
                'PRIMARY_POSITION' => 1,
                'IDENTITY' => true,
            ],
            [
                'COLUMN_NAME' => 'sku',
                'TYPE' => Table::TYPE_TEXT,
                'LENGTH' => 64,
                'NULLABLE' => false,
                'PRIMARY' => false,
            ],
        ]);
        $table->method('getIndexes')->willReturn([]);
        $table->method('getForeignKeys')->willReturn([]);

        $built = $tableSql->createTable($table);

        $this->assertStringContainsString('CREATE TABLE IF NOT EXISTS "catalog_example"', $built['sql']);
        $this->assertStringContainsString('"entity_id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY', $built['sql']);
        $this->assertStringContainsString('"sku" varchar(64) NOT NULL DEFAULT \'\'', $built['sql']);
        $this->assertStringContainsString('PRIMARY KEY ("entity_id")', $built['sql']);
        $this->assertSame([], $built['deferred']);
    }
}
