<?php

declare(strict_types=1);

namespace Morozov\PgCompat\DB\Dialect;

use Magento\Framework\DB\Ddl\Table;

/**
 * Builds a native Postgres column DDL fragment directly from Magento's structured
 * column options - the same $options array Magento\Framework\DB\Adapter\Pdo\Mysql::
 * _getColumnDefinition() receives - instead of rendering MySQL syntax first and
 * regex-translating the resulting string.
 *
 * MySQL's implicit "NOT NULL columns get an implicit zero-ish default outside strict
 * mode" behavior has no Postgres equivalent (Postgres always requires an explicit
 * default or rejects the insert), and a lot of Magento core DDL/data relies on that
 * implicit default existing. Where a NOT NULL column declares no explicit default,
 * this builder backfills one appropriate to the type family, matching the previous
 * regex-based behavior.
 *
 * catalog_product_entity.sku's citext override is deliberately not handled here: it's
 * enforced at runtime by Postgres::ensureCitextSku() on every request regardless of how
 * the column was originally created (imperative Table DDL, declarative schema, or a
 * pre-existing database), so duplicating it at DDL-build time would only be one more
 * place for the two to drift apart.
 */
final class ColumnDefinitionBuilder
{
    public function __construct(private readonly TypeMapper $types)
    {
    }

    /**
     * @param array $options Upper-cased column options (TYPE/LENGTH/PRECISION/SCALE/
     *                        UNSIGNED/NULLABLE/DEFAULT/IDENTITY/AUTO_INCREMENT/COMMENT)
     */
    public function build(string $ddlType, array $options): string
    {
        $pgType = $this->types->toPostgres($ddlType, $options);
        $nullable = array_key_exists('NULLABLE', $options) ? (bool) $options['NULLABLE'] : true;
        $identity = !empty($options['IDENTITY']) || !empty($options['AUTO_INCREMENT']);
        $hasDefault = array_key_exists('DEFAULT', $options) && $options['DEFAULT'] !== false;
        $default = $hasDefault ? $options['DEFAULT'] : null;

        $sql = $pgType;

        if ($identity) {
            // Identity columns are implicitly NOT NULL in Postgres; declaring an explicit
            // "NULL GENERATED BY DEFAULT AS IDENTITY" is a syntax error (conflicting
            // NULL/NOT NULL declarations), so $nullable is intentionally ignored here.
            $sql .= ' NOT NULL GENERATED BY DEFAULT AS IDENTITY';
            return $sql;
        }

        $sql .= $nullable ? ' NULL' : ' NOT NULL';

        if ($ddlType === Table::TYPE_TIMESTAMP || $ddlType === Table::TYPE_DATETIME) {
            $sql .= $this->timestampDefault($default, $nullable);
            return $sql;
        }

        if ($hasDefault) {
            $sql .= $this->explicitDefault($default);
            return $sql;
        }

        if (!$nullable) {
            $sql .= $this->implicitNotNullDefault($pgType);
        }

        return $sql;
    }

    private function timestampDefault($default, bool $nullable): string
    {
        return match (true) {
            $default === null && $nullable => ' DEFAULT NULL',
            $default === Table::TIMESTAMP_INIT,
            $default === Table::TIMESTAMP_UPDATE,
            $default === Table::TIMESTAMP_INIT_UPDATE => ' DEFAULT CURRENT_TIMESTAMP',
            $default === null => " DEFAULT '1970-01-01 00:00:00'",
            default => $this->explicitDefault($default),
        };
    }

    /**
     * Renders a " DEFAULT ..." clause for an explicit default value. Public so the
     * declarative-schema Definition processors (which build their DDL from a different
     * DTO shape but need the exact same default-value quoting rules) can reuse it
     * instead of re-deriving the same policy.
     */
    public function explicitDefault($default): string
    {
        if ($default instanceof \Zend_Db_Expr) {
            return ' DEFAULT ' . $default;
        }
        if ($default === null) {
            return ' DEFAULT NULL';
        }
        if (is_numeric($default)) {
            return ' DEFAULT ' . $default;
        }
        return ' DEFAULT ' . PgIdentifier::quoteValue((string) $default);
    }

    /**
     * Public for the same reason as {@see explicitDefault()}.
     */
    public function implicitNotNullDefault(string $pgType): string
    {
        return match (true) {
            $pgType === 'timestamp' => " DEFAULT '1970-01-01 00:00:00'",
            str_starts_with($pgType, 'varchar'), $pgType === 'text', $pgType === 'jsonb' => " DEFAULT ''",
            in_array($pgType, ['smallint', 'integer', 'bigint', 'real', 'double precision'], true),
            str_starts_with($pgType, 'numeric') => ' DEFAULT 0',
            default => '',
        };
    }
}
