<?php

declare(strict_types=1);

namespace Morozov\PgCompat\DB\Connection;

use Magento\Framework\DB\Adapter\AdapterInterface;

/**
 * Postgres identity columns (GENERATED BY DEFAULT AS IDENTITY, used for every
 * MySQL AUTO_INCREMENT column) back onto a real sequence, which core's frequent
 * "INSERT with an explicit id" pattern (data patches, fixtures, id-preserving imports)
 * does not advance. Left alone, the next identity-generated insert collides with a
 * previously-explicit id. After every INSERT touching an identity column, this bumps
 * that column's sequence to at least the current max - the equivalent of what MySQL's
 * AUTO_INCREMENT bookkeeping does automatically on an explicit-id insert.
 */
final class IdentitySynchronizer
{
    public function syncAfterInsert(\PDO $connection, AdapterInterface $adapter, string $sql): void
    {
        if (!preg_match('/^\s*INSERT\s+INTO\s+"?([a-zA-Z0-9_]+)"?\s*\(([^)]+)\)/is', $sql, $m)) {
            return;
        }
        $table = $m[1];
        $insertedColumns = strtolower($m[2]);
        foreach ($adapter->describeTable($table) as $column => $info) {
            $columnMentioned = preg_match('/"?' . preg_quote(strtolower($column), '/') . '"?/', $insertedColumns);
            if (empty($info['IDENTITY']) || !$columnMentioned) {
                continue;
            }
            $connection->exec(sprintf(
                'SELECT setval(pg_get_serial_sequence(%s, %s), GREATEST(COALESCE((SELECT MAX(%s) FROM %s), 1), 1))',
                $adapter->quote($table),
                $adapter->quote($column),
                $adapter->quoteIdentifier($column),
                $adapter->quoteIdentifier($table)
            ));
        }
    }

    public function resolveLastInsertId(\PDO $connection, AdapterInterface $adapter, ?string $tableName, ?string $primaryKey): string
    {
        $tableName = $tableName ? trim($tableName, '"') : null;
        if ($tableName) {
            if (!$primaryKey) {
                foreach ($adapter->describeTable($tableName) as $column => $info) {
                    if (!empty($info['IDENTITY'])) {
                        $primaryKey = $column;
                        break;
                    }
                }
            }
            if ($primaryKey) {
                try {
                    $seq = $connection->query(
                        'SELECT pg_get_serial_sequence(' . $adapter->quote($tableName) . ', ' . $adapter->quote($primaryKey) . ')'
                    )->fetchColumn();
                    if ($seq) {
                        return (string) $connection->query('SELECT currval(' . $adapter->quote($seq) . ')')->fetchColumn();
                    }
                } catch (\Exception $e) {
                    // No sequence for this column (or none currval'd yet in this session) - fall through.
                }
            }
        }
        try {
            return (string) $connection->query('SELECT lastval()')->fetchColumn();
        } catch (\Exception $e) {
            return '0';
        }
    }
}
